### ISSUE TITLE
Disable opening edit_post_link in new window if Customize Posts plugin is active

### ISSUE THREAD

**Issue by westonruter** [Automattic/customize-direct-manipulation#22]
The [Customize Posts](https://github.com/xwp/wp-customize-posts) adds post editing into the customizer. It includes an integration so that when the edit post link is clicked in the preview, it will load the customizer section for that post and expand it so that it can be edited, directly in the customizer.

Here's an old demo video (from an early version) depicting this:

[![Demo of edit post link click](https://img.youtube.com/vi/nYfph3NbNCc/maxresdefault.jpg)](https://youtu.be/nYfph3NbNCc)

All of this to say, if the Customize Posts feature plugin is active, then the opening of edit post links in a new window behavior in the DM plugin should be disabled.

**Comment by sirbrillig** [comment]
That's probably a good idea. 

Also, this repo contains a disabled feature which adds blue DM buttons to each post: https://github.com/Automattic/customize-direct-manipulation/blob/master/src/modules/post-focus.js

The buttons link right now to the post editor.

We disabled it for launch because we weren't sure the feature would be helpful in its current form.
