### ISSUE TITLE
Defer to and integrate with new edit shortcuts in core

### ISSUE THREAD

**Issue by westonruter** [Automattic/customize-direct-manipulation#37]
Edit shortcuts have been added to core in [r38967](https://core.trac.wordpress.org/changeset/38967). CDM should either short-circuit or extend what is in core if on WP 4.7-beta1 or greater.

**Comment by sirbrillig** [comment]
Wow, I totally missed this issue. 😩  Conveniently, I'm now working on exactly this.

I think ultimately we'd like to switch to using the edit shortcuts instead of this plugin, but for the initial merge, I think it's better to just keep WP.com working the same way and then migrate carefully. To this end I'd like to find a way to disable the edit shortcuts. I already forgot if there's a built-in way to do that, although I don't remember adding any. I'm starting to look now.

**Comment by westonruter** [comment]
See also conversation on WP Slack: https://wordpress.slack.com/archives/core-customize/p1480377695001262
